apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nuevo-servicio-reto3
  description: "Microservicio nuevo-servicio-reto3 — generado via Backstage Golden Path"
  annotations:
    github.com/project-slug: group:default/grupo-5/nuevo-servicio-reto3
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - microservicio
spec:
  type: service
  lifecycle: experimental
  owner: group:default/grupo-5
  system: plataforma-uniandes
